name: Deploy
on:
  release:
    types: [published]

jobs:
  release:
    name: Build and Deploy
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - uses: actions/cache@v3
        id: node-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        run: npm ci
      - name: build and deploy
        env:
          version: ${{ env.GITHUB_REF_NAME }}
        run: npm run deploy