name: Release
on:
  push:
    branches:
      - main
      - next
      - beta
      - alpha


jobs:
  release:
    name: Release
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v3
        id: node-cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: build
        env:
          BEFORE_SHA: ${{ github.event.before }}
        run: npm run build -- --base=$BEFORE_SHA
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          BEFORE_SHA: ${{ github.event.before }}
        run: npm run release -- --base=$BEFORE_SHA
